[package]
name = "caff"
version = "0.1.0"
authors = ["pandaman64 <kointosudesuyo@infoseek.jp>"]
edition = "2018"

license = "MIT OR Apache-2.0"
description = "Capabilities via Algebraic Effects"
repository = "https://github.com/pandaman64/caff/"

[dependencies]
